env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[e5639a37e8afbda65b3a20066cbc54a05b5161b7ef88fe4327c7ca9711d9f1a9263081eb600861c1e038ba3a648af919]"
  TG_TOKEN: "ENCRYPTED[1aa8a68e8d24caa162af90768f8e73423eef7314ef7b7daaf21987169a583ec58bbfa95d90613569eae110fdd0036ac8]"
  TG_CHAT_ID: "ENCRYPTED[758f05e53b09983db8a8ca80e2a9c9f01d2f54086001a9261f13f7340235a576e422ba8bf1ddaab96924749fd031157c]"
  CREDENTIALS: "ENCRYPTED[0c7f59502bc66606e83696f0908d8c80eeab692bb7bfb95e6910d57bc473490d73eef06e0770ae0c8b9c6a11b219e821]"
  USER: "ENCRYPTED[48d7006b8935d79d14287bcae9d762b50bdb1434b6c37048c918a3fd5e5ba9e3e509e2f8ac5c96ee544fb3e622fa5404]"
  EMAIL: "ENCRYPTED[c5b824f3abe58ff89279d82aaaaa8ed5e3538ad7b12a6e1fdc1dbf3ec0412b79484b8b7c6dbe0a531f90e8328815ca5a]"
  KBUILD_BUILD_USER: "ENCRYPTED[fc8cf637fbda9d4423a2dc5f828a94ab4e056343249884f333f0318dc8de1229b53eb263874c395ea07b676db832ba01]"
  KBUILD_BUILD_HOST: "ENCRYPTED[18960fa86f9d95e35b448a62ff7cb7656cf9d1fa62c875d471ce5a9e3f4b1d309e035256268fa7699bb08e690e47ce09]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'IQ-7'
  timeout_in: 120m
  container:
    image: zacky46/ubuntu:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/memuat_ccache.sh
     
  Repo-pribadi_script:
     - git config --global user.name "$USER"
     - git config --global user.email "$EMAIL"
     - echo "$CREDENTIALS" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - export KBUILD_BUILD_USER=$KBUILD_BUILD_USER
     - export KBUILD_BUILD_HOST=$KBUILD_BUILD_USER
     - export BUILD_USERNAME=$KBUILD_BUILD_USER
     - export BUILD_HOSTNAME=$KBUILD_BUILD_USER
     
  Sinkronisasi_script:
     - ./script/sinkronisasi.sh
     
  Build-rom_script:
     - ./script/membangun.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s
     
  Upload-build_script:
     - ./script/mengemas.sh
     
